config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'registrations'
     }
  root to: 'pages#home'
  get '/profile', to: 'users#profile'
  resources :assessments
  get '/result', to: 'assessments#display'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :programs
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_many :programs
  validates :name, uniqueness: true, presence: true
  validates :content
  validates :catergory
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :assessment
  belongs_to :exercise
end

app/models/tip.rb
class Tip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :assessments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery :except => :receive_guest

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_in_path_for(resource)
    logging_in
    profile_path
  end
  # if user is logged in, return current_user, else return guest_user
  def current_or_guest_user
    if current_user
      if session[:guest_user_id] && session[:guest_user_id] != current_user.id
        logging_in
        # reload guest_user to prevent caching problems before destruction
        guest_user(with_retry = false).try(:reload).try(:destroy)
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  def guest_user(with_retry = true)
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
     session[:guest_user_id] = nil
     guest_user if with_retry
  end

  def create
    super
    current_or_guest_user
  end

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

  private
  # called (once) when the user logs in, insert any code your application needs
  # to hand off from guest_user to current_user.
  def logging_in
    # For example:
    # guest_comments = guest_user.comments.all
    # guest_comments.each do |comment|
      # comment.user_id = current_user.id
      # comment.save!
    # end
    guest_assessments = guest_user.assessments.all
    guest_assessments.each do |assessment|
      assessment.user_id = current_user.id
      assessment.save!
    end
  end

  def create_guest_user
    u = User.new(:name => "guest", :email => "guest_#{Time.now.to_i}#{rand(100)}@example.com")
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end

end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :show, :display]

  def new
    @assessment = Assessment.new
  end
  def create
    # if @assessment.angle1? && @assessment.angle2? && @assessment.angle3? == false
    #   render :new
    # end
    exercise_array = []
    @assessment = Assessment.new(assessment_params)
    @assessment.user = current_or_guest_user
    @assessment.photo = change_img_params(assessment_params[:"photo"])
    @assessment.save!
    if (@assessment.angle1 - 180).abs > 5
      exercise_array += Exercise.where(category:"neck")
    end
    if (@assessment.angle2 - 180).abs > 5
      exercise_array += Exercise.where(category:"back")
    end
    exercise_array.uniq.each do |e|
      @program = Program.new
      @program.assessment = @assessment
      @program.exercise = e
      @program.save!
    end
    unless current_user
      session[:guest_user_id] = guest_user.id
    end
    session[:assessment_id] = @assessment.id
    redirect_to result_path(@assessment)
  end

  # def show
  #   @assessment = Assessment.find(params[:id])
  #   @programs = @assessment.programs[0..2]
  # end

  def display
    @assessment = Assessment.find(session[:assessment_id])
    @programs = @assessment.programs[0..2]
  end

  def destroy
    @assessment = Assessment.find(params[:id])
    @assessment.destroy
    redirect_to profile_path
  end



  private

  def assessment_params
    params.require(:assessment).permit(:angle1,:angle2,:angle3,:photo)
  end

  def change_img_params(img)
    begin
    Base64.decode64(img) #To check if thats a base64 string
      if img
        img = file_decode(img.split(',')[1],"some file name") #getting only the string leaving out the data/<format>
      end
      rescue Exception => e
      img #Returning if its not a base64 string
      end
  end

  def file_decode(base, filename)
    file = Tempfile.new([file_base_name(filename), file_extn_name(filename)])
    file.binmode
    file.write(Base64.decode64(base))
    file.close
    file
  end

  def file_base_name(file_name)
    File.basename(file_name, file_extn_name(file_name))
  end

  def file_extn_name(file_name)
    File.extname(file_name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def profile
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  # def after_sign_up_path_for(resource)
  #   '/profile'
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    # @user.assessments << session[:assessment]

     # guest = User.find(session[:guest_user_id])
     # guest_assessments = guest.assessments
     #  guest_assessments.each do |assessment|
     #  assessment.user_id = current_user.id
     #  assessment.save!
    # end
  end

  def profile
    @user = current_user
    @tip = Tip.all.sample.content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/assessments/display.html.erb
<% content_for :meta_title, "your results" %>
<% content_for :meta_description %>
<% content_for :meta_image %>

<div class="wrapper-flex">
  <div class="show-container">
    <div class="show-profile text-center">
      <div class="show-main">
        <%= image_tag @assessment.photo.url %>
      </div>
      <div class="stat">
        <div class="stat-content">
         <h3>Shoulder angle: </h3>
          <h4><% if (175..180).include?(@assessment.angle1) %>
            <div class="green"> <%= @assessment.angle1.to_i %>° </div>
          <% elsif (170..175).include?(@assessment.angle1) %>
            <div class="orange"><%= @assessment.angle1.to_i %>°  </div>
          <% else %>
            <div class="red"><%= @assessment.angle1.to_i %>°  </div>
          <% end %></h4>
          <p class="showp">Optimal: 180°</p>
          <%= image_tag "human-neck.png" %>
        </div>
      </div>
      <div class="stat">
        <div class="stat-content">
          <h3>Hip angle: </h3>
          <h4><% if (175..180).include?(@assessment.angle2) %>
            <div class="green"> <%= @assessment.angle2.to_i %>° </div>
          <% elsif (170..175).include?(@assessment.angle2) %>
            <div class="orange"><%= @assessment.angle2.to_i %>°  </div>
          <% else %>
            <div class="red"><%= @assessment.angle2.to_i %>°  </div>
          <% end %></h4>
          <p class="showp">Optimal: 180°</p>
          <%= image_tag "human-body-side.png" %>
          </div>
        </div>
      <div class="stat">
        <div class="stat-content">
          <h3>Knee angle:</h3>
         <h4> <% if (175..180).include?(@assessment.angle3) %>
            <div class="green"> <%= @assessment.angle3.to_i %>° </div>
          <% elsif (170..175).include?(@assessment.angle3) %>
            <div class="orange"><%= @assessment.angle3.to_i %> °</div>
          <% else %>
            <div class="red"><%= @assessment.angle3.to_i %>°</div>
          <% end %> </h4>
          <p class="showp">Optimal: 180°</p>
          <%= image_tag "men-leg.png" %>
        </div>
      </div>
      <div class="description">
        <div class="description-content">
          <h3>HOW IS YOUR POSTURE?</h3>
          <p class="text-justify">
            Your personal account offers great features tailored to your specific needs such as customizable reminders, recommended exercises, analytical improvements, and much more.
          </p>
          <% if user_signed_in? %>
            <%= link_to "Profile page", profile_path(current_user), class: "btn btn-show" %>
          <% else %>
            <%= link_to "Sign Up Now!", new_user_registration_path,class: "btn btn-show" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/assessments/new.html.erb
<% content_for :meta_title, "Assess yourself" %>
<% content_for :meta_description %>
<% content_for :meta_image %>

<div class="container cam-big-contriner">
  <div class="row">
    <h2>Check Posture Cam</h2>
    <h4 class="text-center">The check cam will evaluate your posture as viewed from the side, please read the instructions for better results.</h5>
  </div>
  <div class="main-container">
    <div class="instructions-container">
      <h3 class="text-center">Instructions:</h3>
      <ol id="instruction1">
        <li> <h5> Adjust the camera angle to 90° </h5> </li>
        <li> <h5> Click on the camera button </h5> </li>
        <li> <h5> Take 4-5 steps back for a head-to-toe view </h5> </li>
        <li> <h5> Face sideways, look straight ahead </h5> </li>
        <li style="list-style-type: none"> <h5> (Photo will be taken 5 seconds after you press the camera button) </h5> </li>
        <li style="list-style-type: none"> <button id="button1" onclick="snapshot(); hideVideo(); countdown(); hideInstructionOne(); appearInstructionTwo(); "> <%= image_tag "camera.png" %> </button> </li>
      </ol>

      <div class="countdown" id="countdown"></div>

      <%= simple_form_for @assessment, html: { class: "hidden", id: :hidden } do |f| %>
        <%= f.input :angle1, as: :hidden %>
        <%= f.input :angle2, as: :hidden %>
        <%= f.input :angle3, as: :hidden %>
        <%= f.input :photo, as: :hidden %>
        <h5>1. Using the example as a guide, please click on the following listed points in your photo </h5>
        <h5>2. After clicking all 5 points, press "Submit for results" </h5>
        <div class="body-points-wraper">
          <div class="body-points">
            <ul>
            <li><h5> <%= image_tag "cursor.png" %> Ear </h5></li>
            <li><h5> <%= image_tag "cursor.png" %> Shoulder </h5></li>
            <li><h5> <%= image_tag "cursor.png" %> Hip </h5></li>
            <li><h5> <%= image_tag "cursor.png" %> Knee </h5></li>
            <li><h5> <%= image_tag "cursor.png" %> Ankle </h5></li></ul>
          </div>
          <div class="samplep">
          <%= cl_image_tag("samplep.jpg.gif", :class => "body-img") %>
          <p>Example</p>
          </div>
        </div>
          <%= f.button :submit, "Submit for results", class: "btn", id: "submitForm" %>


      <% end %>
    </div>
    <div class="camera-container text-center">
      <body onload="init(); startWebcam(); buttonDisable();">
      <!--     <button onclick="stopWebcam();">Stop WebCam</button>-->
      <video width=800 height=600 id="video" autoplay></video>
      <canvas  id="myCanvas" width="800" height="600"></canvas>
    </div>
  </div>
</div>

<!-- Button trigger modal -->

app/views/assessments/show.html.erb
<% content_for :meta_title, "your results" %>
<% content_for :meta_description %>
<% content_for :meta_image %>

<h3 class="text-center">Results</h3>

<div class="show-container">
      <div class="show-profile text-center">
        <div class="show-main">
          <%= image_tag @assessment.photo.url %>
        </div>
        <div class="stat">
          <div class="stat-content">
            Shoulder angle:
            <% if (175..180).include?(@assessment.angle1) %>
              <div class="green"> <%= @assessment.angle1.to_i %> </div>
            <% elsif (170..175).include?(@assessment.angle1) %>
              <div class="orange"><%= @assessment.angle1.to_i %> </div>
            <% else %>
              <div class="red"><%= @assessment.angle1.to_i %> </div>
            <% end %>
            <p class="showp">Optimal: 180</p>
          </div>
        </div>
        <div class="stat">
          <div class="stat-content">
            Hip angle:
            <% if (175..180).include?(@assessment.angle2) %>
              <div class="green"> <%= @assessment.angle2.to_i %> </div>
            <% elsif (170..175).include?(@assessment.angle2) %>
              <div class="orange"><%= @assessment.angle2.to_i %> </div>
            <% else %>
              <div class="red"><%= @assessment.angle2.to_i %> </div>
            <% end %>
            <p class="showp">Optimal angle=180</p>
            </div>
          </div>
        <div class="stat">
          <div class="stat-content">
            Knee angle:
            <% if (175..180).include?(@assessment.angle3) %>
              <div class="green"> <%= @assessment.angle3.to_i %> </div>
            <% elsif (170..175).include?(@assessment.angle3) %>
              <div class="orange"><%= @assessment.angle3.to_i %> </div>
            <% else %>
              <div class="red"><%= @assessment.angle3.to_i %> </div>
            <% end %>
            <p class="showp">Optimal angle=180</p>
          </div>
        </div>
        <div class="description">
          <div class="description-content">
            <h3>Sign up for PostureIt</h3>
            <p class="text-justify">
              PostureIt is your posture buddy at your office or anywhere you're sitting now and reading this. PostureIt will remind to sit up straight .
            </p>
            <% if user_signed_in? %>
              <%= link_to "Profile page", user_path(current_user), class: "btn btn-show" %>
            <% else %>
              <%= link_to "Create an account for more", new_user_registration_path,class: "btn btn-show" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <link rel="icon" type="image/png" sizes="32x32" href="/"> -->
    <%= favicon_link_tag 'favicon-32x32.png' %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <title>Check</title> -->
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="page-wrap">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper-banner">
  <div id="banner">
    <div class="banner-content">
      <h1>CHECK</h1>

      <h3 class="h3-home">Balanced Mind, Balanced Body</h3>
      <%= link_to "Start", new_assessment_path, class: "btn-home"  %>
    </div>
  </div>
</div>

<body class="pbody">
  <section class="section section-dark">
    <h2>Why Posture Matters</h2>
    <p>
      Sitting and standing with proper postural alignment will allow one to work more efficiently with less fatigue and strain on your body's ligaments and muscles.
    </p>

  </section>
  <div class="pimg1">
    <div class="ptext">
      <span class="border">

      </span>
    </div>
  </div>
  <section class="section section-light">
<!--     <h2> How It Works </h2> -->
    <!-- <p>
      Being aware of good posture is the first step to breaking old poor postural habits and reducing stress and strain on your spine. CheckIT is a great feature that will remingd to sit up staright while you work.
    </p> -->
   <div class="home-container">
     <div class="home-steps text-center">
      <div class="step1">
        <%= image_tag "photo-camera.png"%>
        <h3>Assess your posture</h3>
        <p>Quick screen and analysis</p>
      </div>
      <div class="step2">
        <%= image_tag "analysis.png"%>
        <h3>Monitor progress</h3>
        <p>Body composition analysis along with measurment details</p>
        <%= link_to "Start", new_assessment_path, class: "call-to-action btn-home "  %>
      </div>
      <div class="step3">
        <%= image_tag "chatting.png"%>
        <h3>Get notifications</h3>
        <p>Daily reminders of posture awareness
      </div>

     </div>
   </div>

  </section>

<section>
    <div class="pimg2">
     <div class="ptext">
       <span class="border">
       </span>
     </div>
   </div>
</section>

</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2018 Check, Inc.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Links when logged in -->
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x3" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <!-- <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->

  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% else %>
          <li> <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<% content_for :meta_title, "CheckIT" %>
<% content_for :meta_description %>
<% content_for :meta_image %>
 <%= javascript_include_tag "notification" %>

  <!-- <div class="wrapper-main"> -->
  <div class="container-profile text-center">
    <div class="profile-dashboard">
      <div class="profile">
        <div class="profile-body">
          <div class="profile-title">
            <!-- <h3>Profile</h3> -->
          </div>
          <div class="profile-avatar">
            <h3>Welcome back  <%= current_user.first_name %>!</h3>
            <% if current_user.facebook_picture_url == nil %>
            <%= image_tag "profile.png", class: "dashboard-avatar" %>
            <% else %>
            <%= image_tag current_user.facebook_picture_url, class: "dashboard-avatar" %>
            <% end %>
          </div>
        </div>
        <div class="form-group notification-body">
            <h3>CheckIT </h3>
            <h4>Your personal posture reminder</h4>
            <label for="pb-time">How often do you want to be reminded (in minutes)</label>
            <select class="form-control text-center"  id="pb-time-select">
              <option>0.5</option>
              <option>15</option>
              <option>30</option>
              <option>45</option>
              <option>60</option>
            </select>
            <button onclick="notifyMe()" class="btn btn-primary">Start</button>
          </div>
        </div>
      <div class="photos">
        <div class="photos-title">
          <h3>Photos</h3>
        </div>
        <div class="photos-img">
          <% a1 = @user.assessments.first %>
          <% a2 = @user.assessments.last %>
          <div class="a1">
            <p>First Pic</p>
          <%= cl_image_tag a1.photo %>
          </div>
          <% unless a1 == a2 %>
            <div class="a2">
              <p>Latest Pic</p>
            <%= cl_image_tag a2.photo %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="tips">
        <div class="tips-title">
          <h3> Posture Tip </h3>
        </div>
        <div class="tips-content">
          <p>"<%= @tip %>"</p>
        </div>
      </div>
      <div class="exercises">
        <div class="exercises-title">
          <h3>Exercises</h3>
        </div>
        <div class="exercises-content">
          <% if current_user.assessments.last != nil %>
            <% current_user.assessments.last.programs.sample(3).each do |program| %>
              <iframe class="embed-responsive-item youtube-box" src=  <%= program.exercise.content %> frameborder="0" allowfullscreen=""></iframe>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="records">
        <div class="records-title">
          <h3>Latest Records</h3>
        </div>
        <div class="records-content">
        <% assessment = @user.assessments.last %>
          <div class="stat">
            <div class="stat-content">
             <h3>Shoulder angle: </h3>
             <% if assessment != nil %>
              <h4><% if (175..180).include?(assessment.angle1) %>
                <div class="green"> <%= assessment.angle1.to_i %>° </div>
              <% elsif (170..175).include?(assessment.angle1) %>
                <div class="orange"><%= assessment.angle1.to_i %>°  </div>
              <% else %>
                <div class="red"><%= assessment.angle1.to_i %>°  </div>
              <% end %></h4>
              <p class="showp">Optimal: 180°</p>
            </div>
          </div>
          <div class="stat">
            <div class="stat-content">
              <h3>Hip angle: </h3>
              <h4><% if (175..180).include?(assessment.angle2) %>
                <div class="green"> <%= assessment.angle2.to_i %>° </div>
              <% elsif (170..175).include?(assessment.angle2) %>
                <div class="orange"><%= assessment.angle2.to_i %>°  </div>
              <% else %>
                <div class="red"><%= assessment.angle2.to_i %>°  </div>
              <% end %></h4>
              <p class="showp">Optimal: 180°</p>
            </div>
          </div>
          <div class="stat">
            <div class="stat-content">
              <h3>Knee angle:</h3>
             <h4> <% if (175..180).include?(assessment.angle3) %>
                <div class="green"> <%= assessment.angle3.to_i %>° </div>
              <% elsif (170..175).include?(assessment.angle3) %>
                <div class="orange"><%= assessment.angle3.to_i %> °</div>
              <% else %>
                <div class="red"><%= assessment.angle3.to_i %>°</div>
              <% end %> </h4>
              <p class="showp">Optimal: 180°</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="empty"></div>
  </div>
  <!-- </div> -->
  <!-- <div class="wrapper-middle-banner"></div> -->
  <!-- <div class="wrapper-bottom-banner"></div> -->